import type { Metadata } from 'next';
import CiaEnrolmentLandingPage from '../../../src/components/LandingPages/CiaEnrolmentLandingPage';

/*
 * /cia-enrollment
 *
 * Generated by migration/generate-routes.js from the pre-migration
 * <MetaTags> props. These tags used to be written by react-helmet-async after
 * hydration; they are now in the server response.
 */
export const metadata: Metadata = {
    title: "CIA Live Weekend Batch | Global Professional Certifications (GPC)",
    description: "Master the Certified Internal Auditor (CIA) Exam with Structured Live Weekend Training. Official Gleim resources, 1,000+ exam-grade MCQs, and unlimited LMS access with mentor Mr. Arpit Garg.",
    alternates: { canonical: "/cia-enrollment" },
    openGraph: {
        title: "CIA Live Weekend Batch | Global Professional Certifications (GPC)",
        description: "Master the Certified Internal Auditor (CIA) Exam with Structured Live Weekend Training. Official Gleim resources, 1,000+ exam-grade MCQs, and unlimited LMS access with mentor Mr. Arpit Garg.",
        url: "/cia-enrollment",
        type: 'website',
    },
    twitter: {
        card: 'summary_large_image',
        title: "CIA Live Weekend Batch | Global Professional Certifications (GPC)",
        description: "Master the Certified Internal Auditor (CIA) Exam with Structured Live Weekend Training. Official Gleim resources, 1,000+ exam-grade MCQs, and unlimited LMS access with mentor Mr. Arpit Garg.",
    },
};

export default function Page() {
    return (
        <CiaEnrolmentLandingPage />
    );
}
