import type { Metadata } from 'next';
import { Suspense } from 'react';

import BlogList from '../../../src/components/Blogs/BlogList';

/*
 * /blogs
 *
 * Generated by migration/generate-routes.js from the pre-migration
 * <MetaTags> props. These tags used to be written by react-helmet-async after
 * hydration; they are now in the server response.
 */
export const metadata: Metadata = {
    title: "Blog & Expert Insights | Global Professional Certifications",
    description: "Stay updated with the latest tips, trends, and success stories in audit, risk management, and professional certifications.",
    alternates: { canonical: "/blogs" },
    openGraph: {
        title: "Blog & Expert Insights | Global Professional Certifications",
        description: "Stay updated with the latest tips, trends, and success stories in audit, risk management, and professional certifications.",
        url: "/blogs",
        type: 'website',
    },
    twitter: {
        card: 'summary_large_image',
        title: "Blog & Expert Insights | Global Professional Certifications",
        description: "Stay updated with the latest tips, trends, and success stories in audit, risk management, and professional certifications.",
    },
};

export default function Page() {
    return (
        /*
         * BlogList calls useSearchParams() to read ?category=. Without a
         * Suspense boundary Next.js refuses to statically render the route and
         * the build fails. fallback={null} because the component renders its own
         * loading state.
         */
        <Suspense fallback={null}>
            <BlogList />
        </Suspense>
    );
}
