import type { Metadata } from 'next';
import { Suspense } from 'react';

import BlogList from '../../../src/components/Blogs/BlogList';
import { client } from '../../../src/lib/sanity/client';
import { getAllPosts, getAllCategories, getAllTags } from '../../../src/lib/sanity/queries';
import type { CmsList } from '../../../src/types/cms';

/*
 * /blogs
 *
 * Generated by migration/generate-routes.js from the pre-migration
 * <MetaTags> props. These tags used to be written by react-helmet-async after
 * hydration; they are now in the server response.
 */
export const metadata: Metadata = {
    title: "Blog & Expert Insights | Global Professional Certifications",
    description: "Stay updated with the latest tips, trends, and success stories in audit, risk management, and professional certifications.",
    alternates: { canonical: "/blogs" },
    openGraph: {
        title: "Blog & Expert Insights | Global Professional Certifications",
        description: "Stay updated with the latest tips, trends, and success stories in audit, risk management, and professional certifications.",
        url: "/blogs",
        type: 'website',
    },
    twitter: {
        card: 'summary_large_image',
        title: "Blog & Expert Insights | Global Professional Certifications",
        description: "Stay updated with the latest tips, trends, and success stories in audit, risk management, and professional certifications.",
    },
};

/** Refresh the list at most once a minute. */
export const revalidate = 60;

export default async function Page() {
    // Same three queries BlogList used to run in the browser. No try/catch on
    // purpose: if Sanity fails during a refresh, Next.js keeps serving the
    // last good version instead of caching an empty list.
    const [posts, categories, tags] = await Promise.all([
        client.fetch<CmsList>(getAllPosts),
        client.fetch<CmsList>(getAllCategories),
        client.fetch<CmsList>(getAllTags),
    ]);

    return (
        /*
         * BlogList reads ?category= through useSearchParams() inside its own
         * small <Suspense> boundary (CategoryFromUrl), so the list itself is in
         * the server HTML. This outer boundary is a safety net: if a future
         * change calls useSearchParams() higher up, the route still builds.
         */
        <Suspense fallback={null}>
            <BlogList
                allPosts={posts ?? []}
                categories={categories ?? []}
                tags={(tags ?? []).filter(Boolean)}
            />
        </Suspense>
    );
}
