import CisaEnrolmentLandingPage from '../../../../src/components/LandingPages/CisaEnrolmentLandingPage';

/*
 * /lp/cisa-enrollment
 *
 * Generated by migration/generate-routes.js from the pre-migration
 * <MetaTags> props. These tags used to be written by react-helmet-async after
 * hydration; they are now in the server response.
 */
export const metadata = {
    title: "CISA Live Interactive Batch | Global Professional Certifications (GPC)",
    description: "Fast-Track Your GRC Career & Command Higher Salaries Globally with CISA Certification. Master 5 ISACA Domains with mentor Mr. Arpit Garg. Starts August 23rd.",
    alternates: { canonical: "/cisa-enrollment" },
    openGraph: {
        title: "CISA Live Interactive Batch | Global Professional Certifications (GPC)",
        description: "Fast-Track Your GRC Career & Command Higher Salaries Globally with CISA Certification. Master 5 ISACA Domains with mentor Mr. Arpit Garg. Starts August 23rd.",
        url: "/cisa-enrollment",
        type: 'website',
    },
    twitter: {
        card: 'summary_large_image',
        title: "CISA Live Interactive Batch | Global Professional Certifications (GPC)",
        description: "Fast-Track Your GRC Career & Command Higher Salaries Globally with CISA Certification. Master 5 ISACA Domains with mentor Mr. Arpit Garg. Starts August 23rd.",
    },
};

export default function Page() {
    return (
        <CisaEnrolmentLandingPage />
    );
}
