import VideoGalleryPage from '../../../src/components/SuccessStories/VideoGalleryPage';

/*
 * /video-gallery
 *
 * Generated by migration/generate-routes.js from the pre-migration
 * <MetaTags> props. These tags used to be written by react-helmet-async after
 * hydration; they are now in the server response.
 */
export const metadata = {
    title: "Hear from our Students - GPC Video Gallery",
    description: "Watch success stories and testimonials from our students.",
    alternates: { canonical: "/video-gallery" },
    openGraph: {
        title: "Hear from our Students - GPC Video Gallery",
        description: "Watch success stories and testimonials from our students.",
        url: "/video-gallery",
        type: 'website',
    },
    twitter: {
        card: 'summary_large_image',
        title: "Hear from our Students - GPC Video Gallery",
        description: "Watch success stories and testimonials from our students.",
    },
};

export default function Page() {
    return (
        <VideoGalleryPage />
    );
}
