import type { Metadata } from 'next';
import Cisa from '../../../../src/components/Courses/Cisa';

/*
 * /courses/cisa
 *
 * Generated by migration/generate-routes.js from the pre-migration
 * <MetaTags> props. These tags used to be written by react-helmet-async after
 * hydration; they are now in the server response.
 */
export const metadata: Metadata = {
    title: "Best CISA Certification in India | Global Professional Certifications",
    description: "Become a certified expert in IT auditing and risk management with our globally recognized best CISA certification course in India.",
    alternates: { canonical: "/courses/cisa" },
    openGraph: {
        title: "Best CISA Certification in India | Global Professional Certifications",
        description: "Become a certified expert in IT auditing and risk management with our globally recognized best CISA certification course in India.",
        url: "/courses/cisa",
        type: 'website',
    },
    twitter: {
        card: 'summary_large_image',
        title: "Best CISA Certification in India | Global Professional Certifications",
        description: "Become a certified expert in IT auditing and risk management with our globally recognized best CISA certification course in India.",
    },
};

export default function Page() {
    return (
        <Cisa />
    );
}
