import type { Metadata } from 'next';
import Cisa from '../../../../src/components/Courses/Cisa';
import { getBrochureSection } from '../../../../src/services/brochure.service';

/*
 * /courses/cisa
 *
 * Generated by migration/generate-routes.js from the pre-migration
 * <MetaTags> props. These tags used to be written by react-helmet-async after
 * hydration; they are now in the server response.
 */
export const metadata: Metadata = {
    title: "Best CISA Certification in India | Global Professional Certifications",
    description: "Become a certified expert in IT auditing and risk management with our globally recognized best CISA certification course in India.",
    alternates: { canonical: "/courses/cisa" },
    openGraph: {
        title: "Best CISA Certification in India | Global Professional Certifications",
        description: "Become a certified expert in IT auditing and risk management with our globally recognized best CISA certification course in India.",
        url: "/courses/cisa",
        type: 'website',
    },
    twitter: {
        card: 'summary_large_image',
        title: "Best CISA Certification in India | Global Professional Certifications",
        description: "Become a certified expert in IT auditing and risk management with our globally recognized best CISA certification course in India.",
    },
};

/** Refresh the brochure content at most once a minute. */
export const revalidate = 60;

export default async function Page() {
    // Brochure content for the CISA section and the "Other Courses" cards, loaded
    // with the same function (and query) the browser used before. No try/catch
    // on purpose: if Sanity fails during a refresh, Next.js keeps serving the
    // last good version instead of the built-in fallback content.
    const [cisa, cia, iap] = await Promise.all([
        getBrochureSection('cisa'),
        getBrochureSection('cia'),
        getBrochureSection('iap'),
    ]);

    return (
        <Cisa brochure={cisa} brochureSections={{ cisa, cia, iap }} />
    );
}
