import ContactUs from '../../../src/components/Contact/ContactUs';

/*
 * /contact
 *
 * Generated by migration/generate-routes.js from the pre-migration
 * <MetaTags> props. These tags used to be written by react-helmet-async after
 * hydration; they are now in the server response.
 */
export const metadata = {
    title: "Contact Us - Global Professional Certifications",
    description: "Reach out to our team for queries, support, or course guidance. We are here to help you achieve your certification goals.",
    alternates: { canonical: "/contact" },
    openGraph: {
        title: "Contact Us - Global Professional Certifications",
        description: "Reach out to our team for queries, support, or course guidance. We are here to help you achieve your certification goals.",
        url: "/contact",
        type: 'website',
    },
    twitter: {
        card: 'summary_large_image',
        title: "Contact Us - Global Professional Certifications",
        description: "Reach out to our team for queries, support, or course guidance. We are here to help you achieve your certification goals.",
    },
};

export default function Page() {
    return (
        <ContactUs />
    );
}
