import type { Metadata } from 'next';
import Crma from '../../../../src/components/Courses/Crma';
import { getBrochureSection } from '../../../../src/services/brochure.service';

/*
 * /courses/crma
 *
 * Generated by migration/generate-routes.js from the pre-migration
 * <MetaTags> props. These tags used to be written by react-helmet-async after
 * hydration; they are now in the server response.
 */
export const metadata: Metadata = {
    title: "CRMA Certification - Global Professional Certifications",
    description: "Advance your career in risk management and assurance with our CRMA course. Learn governance, control, and mitigation techniques with expert guidance.",
    alternates: { canonical: "/courses/crma" },
    openGraph: {
        title: "CRMA Certification - Global Professional Certifications",
        description: "Advance your career in risk management and assurance with our CRMA course. Learn governance, control, and mitigation techniques with expert guidance.",
        url: "/courses/crma",
        type: 'website',
    },
    twitter: {
        card: 'summary_large_image',
        title: "CRMA Certification - Global Professional Certifications",
        description: "Advance your career in risk management and assurance with our CRMA course. Learn governance, control, and mitigation techniques with expert guidance.",
    },
};

/** Refresh the brochure content at most once a minute. */
export const revalidate = 60;

export default async function Page() {
    // Brochure content for the "Other Courses" cards, loaded with the same
    // function (and query) the browser used before. No try/catch on purpose:
    // if Sanity fails during a refresh, Next.js keeps serving the last good
    // version instead of the built-in fallback buttons.
    const [cia, cisa, iap] = await Promise.all([
        getBrochureSection('cia'),
        getBrochureSection('cisa'),
        getBrochureSection('iap'),
    ]);

    return (
        <Crma brochureSections={{ cia, cisa, iap }} />
    );
}
