import Crma from '../../../../src/components/Courses/Crma';

/*
 * /courses/crma
 *
 * Generated by migration/generate-routes.js from the pre-migration
 * <MetaTags> props. These tags used to be written by react-helmet-async after
 * hydration; they are now in the server response.
 */
export const metadata = {
    title: "CRMA Certification - Global Professional Certifications",
    description: "Advance your career in risk management and assurance with our CRMA course. Learn governance, control, and mitigation techniques with expert guidance.",
    alternates: { canonical: "/courses/crma" },
    openGraph: {
        title: "CRMA Certification - Global Professional Certifications",
        description: "Advance your career in risk management and assurance with our CRMA course. Learn governance, control, and mitigation techniques with expert guidance.",
        url: "/courses/crma",
        type: 'website',
    },
    twitter: {
        card: 'summary_large_image',
        title: "CRMA Certification - Global Professional Certifications",
        description: "Advance your career in risk management and assurance with our CRMA course. Learn governance, control, and mitigation techniques with expert guidance.",
    },
};

export default function Page() {
    return (
        <Crma />
    );
}
