import CoursesOverview from '../../../src/components/CoursesOverview/CoursesOverview';

/*
 * /courses
 *
 * Generated by migration/generate-routes.js from the pre-migration
 * <MetaTags> props. These tags used to be written by react-helmet-async after
 * hydration; they are now in the server response.
 */
export const metadata = {
    title: "Certification Courses - Global Professional Certifications",
    description: "Explore globally recognized certification programs like CIA, led by expert mentors and powered by premium content.",
    alternates: { canonical: "/courses" },
    openGraph: {
        title: "Certification Courses - Global Professional Certifications",
        description: "Explore globally recognized certification programs like CIA, led by expert mentors and powered by premium content.",
        url: "/courses",
        type: 'website',
    },
    twitter: {
        card: 'summary_large_image',
        title: "Certification Courses - Global Professional Certifications",
        description: "Explore globally recognized certification programs like CIA, led by expert mentors and powered by premium content.",
    },
};

export default function Page() {
    return (
        <CoursesOverview />
    );
}
