import type { Metadata } from 'next';
import FaqPage from '../../../src/components/FaqPage/FaqPage';

/*
 * /faq
 *
 * Generated by migration/generate-routes.js from the pre-migration
 * <MetaTags> props. These tags used to be written by react-helmet-async after
 * hydration; they are now in the server response.
 */
export const metadata: Metadata = {
    title: "Frequently Asked Questions (FAQs) | Global Professional Certifications",
    description: "Discover answers to common questions about CIA, CISA, CRMA, and IAP certification courses, mentorship, enrollment, and exam preparation at Global Professional Certifications (GPC). Get expert guidance for your risk assurance and advisory career.",
    alternates: { canonical: "/faq" },
    openGraph: {
        title: "Frequently Asked Questions (FAQs) | Global Professional Certifications",
        description: "Discover answers to common questions about CIA, CISA, CRMA, and IAP certification courses, mentorship, enrollment, and exam preparation at Global Professional Certifications (GPC). Get expert guidance for your risk assurance and advisory career.",
        url: "/faq",
        type: 'website',
    },
    twitter: {
        card: 'summary_large_image',
        title: "Frequently Asked Questions (FAQs) | Global Professional Certifications",
        description: "Discover answers to common questions about CIA, CISA, CRMA, and IAP certification courses, mentorship, enrollment, and exam preparation at Global Professional Certifications (GPC). Get expert guidance for your risk assurance and advisory career.",
    },
};

export default function Page() {
    return (
        <FaqPage />
    );
}
