import type { Metadata } from 'next';
import Events from '../../../src/components/Events/Events';
import { client } from '../../../src/lib/sanity/client';
import { urlFor } from '../../../src/lib/sanity/imageBuilder';
import type { CmsList } from '../../../src/types/cms';

/*
 * /events
 *
 * Generated by migration/generate-routes.js from the pre-migration
 * <MetaTags> props. These tags used to be written by react-helmet-async after
 * hydration; they are now in the server response.
 */
export const metadata: Metadata = {
    title: "Upcoming Certification Events & Webinars - GPC",
    description: "Stay updated with live sessions, webinars, and certification events hosted by Global Professional Certifications.",
    alternates: { canonical: "/events" },
    openGraph: {
        title: "Upcoming Certification Events & Webinars - GPC",
        description: "Stay updated with live sessions, webinars, and certification events hosted by Global Professional Certifications.",
        url: "/events",
        type: 'website',
    },
    twitter: {
        card: 'summary_large_image',
        title: "Upcoming Certification Events & Webinars - GPC",
        description: "Stay updated with live sessions, webinars, and certification events hosted by Global Professional Certifications.",
    },
};

/** Refresh the past events at most once a minute. */
export const revalidate = 60;

// Past events (supports both pastEvent and legacy event document types).
// Same query Events.tsx used to run in the browser, moved here unchanged.
const PAST_EVENTS_QUERY = `*[_type in ["pastEvent", "event"] && isActive != false && defined(year)] | order(year desc, order asc) {
                    _id,
                    eventName,
                    "slug": slug.current,
                    title,
                    description,
                    location,
                    date,
                    year,
                    coverImage,
                    galleryImages,
                    order
                }`;

// Upcoming events: the same query LayoutContext runs in the browser (copied
// unchanged). LayoutContext keeps its own copy for the home countdown bar.
const UPCOMING_EVENTS_QUERY = `*[_type == "upcomingEvent" && isActive == true] | order(eventStartDateTime asc) {
                    _id,
                    eventName,
                    title,
                    description,
                    venue,
                    date,
                    eventStartDateTime,
                    registrationLink,
                    registrationButtonText,
                    coverImage
                }`;

export default async function Page() {
    // No try/catch on purpose: if Sanity fails during a refresh, Next.js keeps
    // serving the last good version instead of caching an empty events list.
    const [data, upcomingData] = await Promise.all([
        client.fetch<CmsList>(PAST_EVENTS_QUERY),
        client.fetch<CmsList>(UPCOMING_EVENTS_QUERY),
    ]);

    // Process images with urlFor to respect hotspots/crops (same as before).
    const events = (data ?? []).map(event => ({
        ...event,
        coverImageUrl: event.coverImage ? urlFor(event.coverImage).url() : null,
        galleryImageUrls: event.galleryImages
            ? event.galleryImages.map(img => urlFor(img).url())
            : []
    }));

    // Same rule as LayoutContext: hide events that have already started, and
    // build the cover image URL. UpcomingEventCard re-checks after load, so an
    // event starting between refreshes is still hidden.
    const now = new Date();
    const upcomingEvents = (upcomingData ?? [])
        .filter(event => new Date(event.eventStartDateTime) > now)
        .map(event => ({
            ...event,
            coverImageUrl: event.coverImage ? urlFor(event.coverImage).url() : null,
        }));

    return (
        <Events events={events} upcomingEvents={upcomingEvents} />
    );
}
