import Events from '../../../src/components/Events/Events';

/*
 * /events
 *
 * Generated by migration/generate-routes.js from the pre-migration
 * <MetaTags> props. These tags used to be written by react-helmet-async after
 * hydration; they are now in the server response.
 */
export const metadata = {
    title: "Upcoming Certification Events & Webinars - GPC",
    description: "Stay updated with live sessions, webinars, and certification events hosted by Global Professional Certifications.",
    alternates: { canonical: "/events" },
    openGraph: {
        title: "Upcoming Certification Events & Webinars - GPC",
        description: "Stay updated with live sessions, webinars, and certification events hosted by Global Professional Certifications.",
        url: "/events",
        type: 'website',
    },
    twitter: {
        card: 'summary_large_image',
        title: "Upcoming Certification Events & Webinars - GPC",
        description: "Stay updated with live sessions, webinars, and certification events hosted by Global Professional Certifications.",
    },
};

export default function Page() {
    return (
        <Events />
    );
}
