import type { Metadata } from 'next';
import Journey from '../../../src/components/Journey/Journey';

/*
 * /our-journey
 *
 * Generated by migration/generate-routes.js from the pre-migration
 * <MetaTags> props. These tags used to be written by react-helmet-async after
 * hydration; they are now in the server response.
 */
export const metadata: Metadata = {
    title: "1 Year Journey | CIA Certification Training in India | Global Professional Certifications",
    description: "Celebrating 1 year journey of Global Professional Certifications who help individuals excel in their CIA career journey to earn higher salary and more job opportunities.",
    alternates: { canonical: "/our-journey" },
    openGraph: {
        title: "1 Year Journey | CIA Certification Training in India | Global Professional Certifications",
        description: "Celebrating 1 year journey of Global Professional Certifications who help individuals excel in their CIA career journey to earn higher salary and more job opportunities.",
        url: "/our-journey",
        type: 'website',
    },
    twitter: {
        card: 'summary_large_image',
        title: "1 Year Journey | CIA Certification Training in India | Global Professional Certifications",
        description: "Celebrating 1 year journey of Global Professional Certifications who help individuals excel in their CIA career journey to earn higher salary and more job opportunities.",
    },
};

export default function Page() {
    return (
        <Journey />
    );
}
