import type { Metadata } from 'next';
import Journey from '../../../src/components/Journey/Journey';
import { getBrochureSection } from '../../../src/services/brochure.service';

/*
 * /our-journey
 *
 * Generated by migration/generate-routes.js from the pre-migration
 * <MetaTags> props. These tags used to be written by react-helmet-async after
 * hydration; they are now in the server response.
 */
export const metadata: Metadata = {
    title: "1 Year Journey | CIA Certification Training in India | Global Professional Certifications",
    description: "Celebrating 1 year journey of Global Professional Certifications who help individuals excel in their CIA career journey to earn higher salary and more job opportunities.",
    alternates: { canonical: "/our-journey" },
    openGraph: {
        title: "1 Year Journey | CIA Certification Training in India | Global Professional Certifications",
        description: "Celebrating 1 year journey of Global Professional Certifications who help individuals excel in their CIA career journey to earn higher salary and more job opportunities.",
        url: "/our-journey",
        type: 'website',
    },
    twitter: {
        card: 'summary_large_image',
        title: "1 Year Journey | CIA Certification Training in India | Global Professional Certifications",
        description: "Celebrating 1 year journey of Global Professional Certifications who help individuals excel in their CIA career journey to earn higher salary and more job opportunities.",
    },
};

/** Refresh the brochure content at most once a minute. */
export const revalidate = 60;

export default async function Page() {
    // Brochure content for the "Other Courses" cards, loaded with the same
    // function (and query) the browser used before. No try/catch on purpose:
    // if Sanity fails during a refresh, Next.js keeps serving the last good
    // version instead of the built-in fallback buttons.
    const [cia, cisa, iap] = await Promise.all([
        getBrochureSection('cia'),
        getBrochureSection('cisa'),
        getBrochureSection('iap'),
    ]);

    return (
        <Journey brochureSections={{ cia, cisa, iap }} />
    );
}
