import AboutUs from '../../../src/components/About/AboutUs';

/*
 * /about
 *
 * Generated by migration/generate-routes.js from the pre-migration
 * <MetaTags> props. These tags used to be written by react-helmet-async after
 * hydration; they are now in the server response.
 */
export const metadata = {
    title: "About Global Professional Certifications",
    description: "Learn how we empower professionals with globally recognized certifications and expert-driven learning.",
    alternates: { canonical: "/about" },
    openGraph: {
        title: "About Global Professional Certifications",
        description: "Learn how we empower professionals with globally recognized certifications and expert-driven learning.",
        url: "/about",
        type: 'website',
    },
    twitter: {
        card: 'summary_large_image',
        title: "About Global Professional Certifications",
        description: "Learn how we empower professionals with globally recognized certifications and expert-driven learning.",
    },
};

export default function Page() {
    return (
        <AboutUs />
    );
}
