import type { Metadata } from 'next';
import Iap from '../../../../src/components/Courses/Iap';
import { getBrochureSection } from '../../../../src/services/brochure.service';

/*
 * /courses/iap
 *
 * Generated by migration/generate-routes.js from the pre-migration
 * <MetaTags> props. These tags used to be written by react-helmet-async after
 * hydration; they are now in the server response.
 */
export const metadata: Metadata = {
    title: "IAP Certification - Global Professional Certifications",
    description: "Advance your career in internal auditing with our IAP course. Learn essential auditing principles, ethics, and best practices recognized globally.",
    alternates: { canonical: "/courses/iap" },
    openGraph: {
        title: "IAP Certification - Global Professional Certifications",
        description: "Advance your career in internal auditing with our IAP course. Learn essential auditing principles, ethics, and best practices recognized globally.",
        url: "/courses/iap",
        type: 'website',
    },
    twitter: {
        card: 'summary_large_image',
        title: "IAP Certification - Global Professional Certifications",
        description: "Advance your career in internal auditing with our IAP course. Learn essential auditing principles, ethics, and best practices recognized globally.",
    },
};

/** Refresh the brochure content at most once a minute. */
export const revalidate = 60;

export default async function Page() {
    // Brochure content for the IAP section and the "Other Courses" cards, loaded
    // with the same function (and query) the browser used before. No try/catch
    // on purpose: if Sanity fails during a refresh, Next.js keeps serving the
    // last good version instead of the built-in fallback content.
    const [iap, cia, cisa] = await Promise.all([
        getBrochureSection('iap'),
        getBrochureSection('cia'),
        getBrochureSection('cisa'),
    ]);

    return (
        <Iap brochure={iap} brochureSections={{ iap, cia, cisa }} />
    );
}
