import type { Metadata } from 'next';
import Iap from '../../../../src/components/Courses/Iap';

/*
 * /courses/iap
 *
 * Generated by migration/generate-routes.js from the pre-migration
 * <MetaTags> props. These tags used to be written by react-helmet-async after
 * hydration; they are now in the server response.
 */
export const metadata: Metadata = {
    title: "IAP Certification - Global Professional Certifications",
    description: "Advance your career in internal auditing with our IAP course. Learn essential auditing principles, ethics, and best practices recognized globally.",
    alternates: { canonical: "/courses/iap" },
    openGraph: {
        title: "IAP Certification - Global Professional Certifications",
        description: "Advance your career in internal auditing with our IAP course. Learn essential auditing principles, ethics, and best practices recognized globally.",
        url: "/courses/iap",
        type: 'website',
    },
    twitter: {
        card: 'summary_large_image',
        title: "IAP Certification - Global Professional Certifications",
        description: "Advance your career in internal auditing with our IAP course. Learn essential auditing principles, ethics, and best practices recognized globally.",
    },
};

export default function Page() {
    return (
        <Iap />
    );
}
