import Glossary from '../../../src/components/Glossary/Glossary';

/*
 * /glossary
 *
 * Generated by migration/generate-routes.js from the pre-migration
 * <MetaTags> props. These tags used to be written by react-helmet-async after
 * hydration; they are now in the server response.
 */
export const metadata = {
    title: "Certification Glossary | Key Terms for Auditors & Risk Professionals",
    description: "Explore definitions of essential terms in risk management, internal audit, and advisory careers. This comprehensive glossary from Global Professional Certifications (GPC) helps you master industry language and excel in globally recognized certifications.",
    alternates: { canonical: "/glossary" },
    openGraph: {
        title: "Certification Glossary | Key Terms for Auditors & Risk Professionals",
        description: "Explore definitions of essential terms in risk management, internal audit, and advisory careers. This comprehensive glossary from Global Professional Certifications (GPC) helps you master industry language and excel in globally recognized certifications.",
        url: "/glossary",
        type: 'website',
    },
    twitter: {
        card: 'summary_large_image',
        title: "Certification Glossary | Key Terms for Auditors & Risk Professionals",
        description: "Explore definitions of essential terms in risk management, internal audit, and advisory careers. This comprehensive glossary from Global Professional Certifications (GPC) helps you master industry language and excel in globally recognized certifications.",
    },
};

export default function Page() {
    return (
        <Glossary />
    );
}
