import PrivacyPolicy from '../../../src/components/Privacy/PrivacyPolicy';

/*
 * /privacy
 *
 * Generated by migration/generate-routes.js from the pre-migration
 * <MetaTags> props. These tags used to be written by react-helmet-async after
 * hydration; they are now in the server response.
 */
export const metadata = {
    title: "Privacy Policy – Global Professional Certifications",
    description: "Understand how we protect your data and privacy as you use our platform and enroll in our courses.",
    alternates: { canonical: "/privacy" },
    openGraph: {
        title: "Privacy Policy – Global Professional Certifications",
        description: "Understand how we protect your data and privacy as you use our platform and enroll in our courses.",
        url: "/privacy",
        type: 'website',
    },
    twitter: {
        card: 'summary_large_image',
        title: "Privacy Policy – Global Professional Certifications",
        description: "Understand how we protect your data and privacy as you use our platform and enroll in our courses.",
    },
};

export default function Page() {
    return (
        <PrivacyPolicy />
    );
}
