import type { Metadata } from 'next';
import GtmTrainings from '../../../../src/components/Corporate/GtmTrainings';

/*
 * /corporate/gtm-trainings
 *
 * Generated by migration/generate-routes.js from the pre-migration
 * <MetaTags> props. These tags used to be written by react-helmet-async after
 * hydration; they are now in the server response.
 */
export const metadata: Metadata = {
    title: "Corporate Training Programmes | GTM Trainings | Global Professional Certifications",
    description: "Elevate your team with GPC's 30 specialized corporate training programs. From Risk-Based Auditing to AI and Agile methodologies.",
    alternates: { canonical: "/corporate/gtm-trainings" },
    openGraph: {
        title: "Corporate Training Programmes | GTM Trainings | Global Professional Certifications",
        description: "Elevate your team with GPC's 30 specialized corporate training programs. From Risk-Based Auditing to AI and Agile methodologies.",
        url: "/corporate/gtm-trainings",
        type: 'website',
    },
    twitter: {
        card: 'summary_large_image',
        title: "Corporate Training Programmes | GTM Trainings | Global Professional Certifications",
        description: "Elevate your team with GPC's 30 specialized corporate training programs. From Risk-Based Auditing to AI and Agile methodologies.",
    },
};

export default function Page() {
    return (
        <GtmTrainings />
    );
}
