import Qaip from '../../../../src/components/Corporate/Qaip';

/*
 * /corporate/qaip
 *
 * Generated by migration/generate-routes.js from the pre-migration
 * <MetaTags> props. These tags used to be written by react-helmet-async after
 * hydration; they are now in the server response.
 */
export const metadata = {
    title: "Quality Assessment Improvement Program (QAIP) | GPC in Partnership with IIA India",
    description: "Elevate Internal Audit Excellence with IIA Quality Assessments. Ensure conformance with Global Internal Audit Standards. GPC in partnership with IIA India.",
    alternates: { canonical: "/corporate/qaip" },
    openGraph: {
        title: "Quality Assessment Improvement Program (QAIP) | GPC in Partnership with IIA India",
        description: "Elevate Internal Audit Excellence with IIA Quality Assessments. Ensure conformance with Global Internal Audit Standards. GPC in partnership with IIA India.",
        url: "/corporate/qaip",
        type: 'website',
    },
    twitter: {
        card: 'summary_large_image',
        title: "Quality Assessment Improvement Program (QAIP) | GPC in Partnership with IIA India",
        description: "Elevate Internal Audit Excellence with IIA Quality Assessments. Ensure conformance with Global Internal Audit Standards. GPC in partnership with IIA India.",
    },
};

export default function Page() {
    return (
        <Qaip />
    );
}
