import type { Metadata } from 'next';
import RefundPolicy from '../../../src/components/Refund/RefundPolicy';

/*
 * /refund
 *
 * Generated by migration/generate-routes.js from the pre-migration
 * <MetaTags> props. These tags used to be written by react-helmet-async after
 * hydration; they are now in the server response.
 */
export const metadata: Metadata = {
    title: "Refund Policy – Global Professional Certifications",
    description: "Review our refund and cancellation policy before enrolling. We aim to ensure a smooth learning experience.",
    alternates: { canonical: "/refund" },
    openGraph: {
        title: "Refund Policy – Global Professional Certifications",
        description: "Review our refund and cancellation policy before enrolling. We aim to ensure a smooth learning experience.",
        url: "/refund",
        type: 'website',
    },
    twitter: {
        card: 'summary_large_image',
        title: "Refund Policy – Global Professional Certifications",
        description: "Review our refund and cancellation policy before enrolling. We aim to ensure a smooth learning experience.",
    },
};

export default function Page() {
    return (
        <RefundPolicy />
    );
}
