import type { Metadata } from 'next';
import CiaCampaign from '../../../src/components/Courses/CiaCampaign';
import { getBrochureSection } from '../../../src/services/brochure.service';

/*
 * /cia-campaign
 *
 * Generated by migration/generate-routes.js from the pre-migration
 * <MetaTags> props. These tags used to be written by react-helmet-async after
 * hydration; they are now in the server response.
 */
export const metadata: Metadata = {
    title: "CIA Certification Training | India's #1 IIA-Accredited Program",
    description: "Join the most trusted CIA certification training in India. 350+ success stories, US Gleim content, and live mentorship by Arpit Garg. Enroll now!",
    alternates: { canonical: "/cia-campaign" },
    openGraph: {
        title: "CIA Certification Training | India's #1 IIA-Accredited Program",
        description: "Join the most trusted CIA certification training in India. 350+ success stories, US Gleim content, and live mentorship by Arpit Garg. Enroll now!",
        url: "/cia-campaign",
        type: 'website',
    },
    twitter: {
        card: 'summary_large_image',
        title: "CIA Certification Training | India's #1 IIA-Accredited Program",
        description: "Join the most trusted CIA certification training in India. 350+ success stories, US Gleim content, and live mentorship by Arpit Garg. Enroll now!",
    },
};

/** Refresh the brochure content at most once a minute. */
export const revalidate = 60;

export default async function Page() {
    // CIA brochure section content, loaded with the same function (and query)
    // the browser used before. No try/catch on purpose: if Sanity fails during a
    // refresh, Next.js keeps serving the last good version instead of the
    // built-in fallback content.
    const cia = await getBrochureSection('cia');

    return (
        <CiaCampaign brochure={cia} />
    );
}
