import CiaCampaign from '../../../src/components/Courses/CiaCampaign';

/*
 * /cia-campaign
 *
 * Generated by migration/generate-routes.js from the pre-migration
 * <MetaTags> props. These tags used to be written by react-helmet-async after
 * hydration; they are now in the server response.
 */
export const metadata = {
    title: "CIA Certification Training | India's #1 IIA-Accredited Program",
    description: "Join the most trusted CIA certification training in India. 350+ success stories, US Gleim content, and live mentorship by Arpit Garg. Enroll now!",
    alternates: { canonical: "/cia-campaign" },
    openGraph: {
        title: "CIA Certification Training | India's #1 IIA-Accredited Program",
        description: "Join the most trusted CIA certification training in India. 350+ success stories, US Gleim content, and live mentorship by Arpit Garg. Enroll now!",
        url: "/cia-campaign",
        type: 'website',
    },
    twitter: {
        card: 'summary_large_image',
        title: "CIA Certification Training | India's #1 IIA-Accredited Program",
        description: "Join the most trusted CIA certification training in India. 350+ success stories, US Gleim content, and live mentorship by Arpit Garg. Enroll now!",
    },
};

export default function Page() {
    return (
        <CiaCampaign />
    );
}
