import type { Metadata } from 'next';
import Cia from '../../../../src/components/Courses/Cia';

/*
 * /courses/cia
 *
 * Generated by migration/generate-routes.js from the pre-migration
 * <MetaTags> props. These tags used to be written by react-helmet-async after
 * hydration; they are now in the server response.
 */
export const metadata: Metadata = {
    title: "Become Certified Internal Auditor | Join CIA Certification Training Course in India",
    description: "Pass the CIA challenge exam with live sessions, Gleim content, and expert guidance from Global Professional Certifications, one of India's leading CIA certification training providers.",
    alternates: { canonical: "/courses/cia" },
    openGraph: {
        title: "Become Certified Internal Auditor | Join CIA Certification Training Course in India",
        description: "Pass the CIA challenge exam with live sessions, Gleim content, and expert guidance from Global Professional Certifications, one of India's leading CIA certification training providers.",
        url: "/courses/cia",
        type: 'website',
    },
    twitter: {
        card: 'summary_large_image',
        title: "Become Certified Internal Auditor | Join CIA Certification Training Course in India",
        description: "Pass the CIA challenge exam with live sessions, Gleim content, and expert guidance from Global Professional Certifications, one of India's leading CIA certification training providers.",
    },
};

export default function Page() {
    return (
        <Cia />
    );
}
