import type { Metadata } from 'next';
import Cia from '../../../../src/components/Courses/Cia';
import { getBrochureSection } from '../../../../src/services/brochure.service';

/*
 * /courses/cia
 *
 * Generated by migration/generate-routes.js from the pre-migration
 * <MetaTags> props. These tags used to be written by react-helmet-async after
 * hydration; they are now in the server response.
 */
export const metadata: Metadata = {
    title: "Become Certified Internal Auditor | Join CIA Certification Training Course in India",
    description: "Pass the CIA challenge exam with live sessions, Gleim content, and expert guidance from Global Professional Certifications, one of India's leading CIA certification training providers.",
    alternates: { canonical: "/courses/cia" },
    openGraph: {
        title: "Become Certified Internal Auditor | Join CIA Certification Training Course in India",
        description: "Pass the CIA challenge exam with live sessions, Gleim content, and expert guidance from Global Professional Certifications, one of India's leading CIA certification training providers.",
        url: "/courses/cia",
        type: 'website',
    },
    twitter: {
        card: 'summary_large_image',
        title: "Become Certified Internal Auditor | Join CIA Certification Training Course in India",
        description: "Pass the CIA challenge exam with live sessions, Gleim content, and expert guidance from Global Professional Certifications, one of India's leading CIA certification training providers.",
    },
};

/** Refresh the brochure content at most once a minute. */
export const revalidate = 60;

export default async function Page() {
    // Brochure content for the CIA section and the "Other Courses" cards, loaded
    // with the same function (and query) the browser used before. No try/catch
    // on purpose: if Sanity fails during a refresh, Next.js keeps serving the
    // last good version instead of the built-in fallback content.
    const [cia, cisa, iap] = await Promise.all([
        getBrochureSection('cia'),
        getBrochureSection('cisa'),
        getBrochureSection('iap'),
    ]);

    return (
        <Cia brochure={cia} brochureSections={{ cia, cisa, iap }} />
    );
}
