import type { Metadata } from 'next';
import SuccessStories from '../../../src/components/SuccessStories/SuccessStories';

/*
 * /success
 *
 * Generated by migration/generate-routes.js from the pre-migration
 * <MetaTags> props. These tags used to be written by react-helmet-async after
 * hydration; they are now in the server response.
 */
export const metadata: Metadata = {
    title: "CIA Exam Success Stories – Real Achievements",
    description: "Hear from professionals who passed the CIA Challenge Exam with our guidance. Discover how our course made a difference in their careers.",
    alternates: { canonical: "/success" },
    openGraph: {
        title: "CIA Exam Success Stories – Real Achievements",
        description: "Hear from professionals who passed the CIA Challenge Exam with our guidance. Discover how our course made a difference in their careers.",
        url: "/success",
        type: 'website',
    },
    twitter: {
        card: 'summary_large_image',
        title: "CIA Exam Success Stories – Real Achievements",
        description: "Hear from professionals who passed the CIA Challenge Exam with our guidance. Discover how our course made a difference in their careers.",
    },
};

export default function Page() {
    return (
        <SuccessStories />
    );
}
