import type { Metadata } from 'next';
import WrittenGalleryPage from '../../../src/components/SuccessStories/WrittenGalleryPage';
import { client } from '../../../src/lib/sanity/client';
import type { CmsList } from '../../../src/types/cms';

/*
 * /written-gallery
 *
 * Generated by migration/generate-routes.js from the pre-migration
 * <MetaTags> props. These tags used to be written by react-helmet-async after
 * hydration; they are now in the server response.
 */
export const metadata: Metadata = {
    title: "Written Testimonials - GPC Success Stories",
    description: "Read written testimonials and success stories from our students who transformed their careers.",
    alternates: { canonical: "/written-gallery" },
    openGraph: {
        title: "Written Testimonials - GPC Success Stories",
        description: "Read written testimonials and success stories from our students who transformed their careers.",
        url: "/written-gallery",
        type: 'website',
    },
    twitter: {
        card: 'summary_large_image',
        title: "Written Testimonials - GPC Success Stories",
        description: "Read written testimonials and success stories from our students who transformed their careers.",
    },
};

/** Refresh the written stories at most once a minute. */
export const revalidate = 60;

// Same query WrittenGalleryPage.tsx used to run in the browser, moved here unchanged.
const WRITTEN_STORIES_QUERY = `*[_type == "successStory" && category == "written"] | order(_createdAt desc) {
                    _id,
                    name,
                    company,
                    location,
                    designation,
                    batch,
                    "courseSlug": course->slug.current,
                    "courseName": course->name,
                    category,
                    quote,
                    excerpt,
                    thumbnail,
                    "videoUrl": video.asset->url,
                    image,
                    companyLogo
                }`;

export default async function Page() {
    // No try/catch on purpose: if Sanity fails during a refresh, Next.js keeps
    // serving the last good version instead of an empty gallery.
    const stories = await client.fetch<CmsList>(WRITTEN_STORIES_QUERY);

    return (
        <WrittenGalleryPage stories={stories ?? []} />
    );
}
