import WrittenGalleryPage from '../../../src/components/SuccessStories/WrittenGalleryPage';

/*
 * /written-gallery
 *
 * Generated by migration/generate-routes.js from the pre-migration
 * <MetaTags> props. These tags used to be written by react-helmet-async after
 * hydration; they are now in the server response.
 */
export const metadata = {
    title: "Written Testimonials - GPC Success Stories",
    description: "Read written testimonials and success stories from our students who transformed their careers.",
    alternates: { canonical: "/written-gallery" },
    openGraph: {
        title: "Written Testimonials - GPC Success Stories",
        description: "Read written testimonials and success stories from our students who transformed their careers.",
        url: "/written-gallery",
        type: 'website',
    },
    twitter: {
        card: 'summary_large_image',
        title: "Written Testimonials - GPC Success Stories",
        description: "Read written testimonials and success stories from our students who transformed their careers.",
    },
};

export default function Page() {
    return (
        <WrittenGalleryPage />
    );
}
