import type { Metadata } from 'next';
import Upcoming from '../../../src/components/Upcoming/Upcoming';
import { isItemActive } from '../../../src/components/Upcoming/upcomingUtils';
import { client } from '../../../src/lib/sanity/client';
import type { CmsList } from '../../../src/types/cms';

/*
 * /upcoming
 *
 * Generated by migration/generate-routes.js from the pre-migration
 * <MetaTags> props. These tags used to be written by react-helmet-async after
 * hydration; they are now in the server response.
 */
export const metadata: Metadata = {
    title: "Upcoming Batches & Webinars | Global Professional Certifications",
    description: "Stay updated with upcoming CIA, CISA, CRMA, and IAP certification batches. Join our global webinars on Risk Management and Internal Audit excellence.",
    alternates: { canonical: "/upcoming" },
    openGraph: {
        title: "Upcoming Batches & Webinars | Global Professional Certifications",
        description: "Stay updated with upcoming CIA, CISA, CRMA, and IAP certification batches. Join our global webinars on Risk Management and Internal Audit excellence.",
        url: "/upcoming",
        type: 'website',
    },
    twitter: {
        card: 'summary_large_image',
        title: "Upcoming Batches & Webinars | Global Professional Certifications",
        description: "Stay updated with upcoming CIA, CISA, CRMA, and IAP certification batches. Join our global webinars on Risk Management and Internal Audit excellence.",
    },
};

/** Refresh the batches at most once a minute. */
export const revalidate = 60;

export default async function Page() {
    // Same two queries Upcoming.tsx used to run in the browser, moved here
    // unchanged. No try/catch on purpose: if Sanity fails during a refresh,
    // Next.js keeps serving the last good version instead of an empty page.
    const [batchesData, announcementsData] = await Promise.all([
        client.fetch<CmsList>(`*[_type == "upcomingBatch" && isActive == true] | order(order asc) { ..., "detailsFileUrl": detailsFile.asset->url }`),
        client.fetch<CmsList>(`*[_type == "upcomingAnnouncement" && isActive == true] | order(order asc)`)
    ]);

    // Hide items whose auto-inactive time has passed, same rule as before.
    // Upcoming re-checks after load, so an item expiring between refreshes
    // is still hidden.
    return (
        <Upcoming
            batches={(batchesData || []).filter(isItemActive)}
            announcements={(announcementsData || []).filter(isItemActive)}
        />
    );
}
