import type { Metadata } from 'next';
import Upcoming from '../../../src/components/Upcoming/Upcoming';

/*
 * /upcoming
 *
 * Generated by migration/generate-routes.js from the pre-migration
 * <MetaTags> props. These tags used to be written by react-helmet-async after
 * hydration; they are now in the server response.
 */
export const metadata: Metadata = {
    title: "Upcoming Batches & Webinars | Global Professional Certifications",
    description: "Stay updated with upcoming CIA, CISA, CRMA, and IAP certification batches. Join our global webinars on Risk Management and Internal Audit excellence.",
    alternates: { canonical: "/upcoming" },
    openGraph: {
        title: "Upcoming Batches & Webinars | Global Professional Certifications",
        description: "Stay updated with upcoming CIA, CISA, CRMA, and IAP certification batches. Join our global webinars on Risk Management and Internal Audit excellence.",
        url: "/upcoming",
        type: 'website',
    },
    twitter: {
        card: 'summary_large_image',
        title: "Upcoming Batches & Webinars | Global Professional Certifications",
        description: "Stay updated with upcoming CIA, CISA, CRMA, and IAP certification batches. Join our global webinars on Risk Management and Internal Audit excellence.",
    },
};

export default function Page() {
    return (
        <Upcoming />
    );
}
