import Terms from '../../../src/components/Terms/Terms';

/*
 * /terms
 *
 * Generated by migration/generate-routes.js from the pre-migration
 * <MetaTags> props. These tags used to be written by react-helmet-async after
 * hydration; they are now in the server response.
 */
export const metadata = {
    title: "Terms & Conditions – Global Professional Certifications",
    description: "Read our terms and conditions outlining course access, use of services, and user responsibilities.",
    alternates: { canonical: "/terms" },
    openGraph: {
        title: "Terms & Conditions – Global Professional Certifications",
        description: "Read our terms and conditions outlining course access, use of services, and user responsibilities.",
        url: "/terms",
        type: 'website',
    },
    twitter: {
        card: 'summary_large_image',
        title: "Terms & Conditions – Global Professional Certifications",
        description: "Read our terms and conditions outlining course access, use of services, and user responsibilities.",
    },
};

export default function Page() {
    return (
        <Terms />
    );
}
